#!/bin/sh
set -e

# Configure pg_hba.conf based on SSL_MODE

SSL_MODE="${SSL_MODE:-verify-ca}"
PGDATA="${PGDATA:-/var/lib/postgresql/data}"

echo "Configuring pg_hba.conf (SSL_MODE=$SSL_MODE)..."

cat > "$PGDATA/pg_hba.conf" << EOF
# PostgreSQL Client Authentication Configuration
# Generated by postgres-tls container (SSL_MODE=$SSL_MODE)

# Local connections (Unix socket)
local   all             all                                     trust
EOF

case "$SSL_MODE" in
    prefer)
        cat >> "$PGDATA/pg_hba.conf" << EOF

# Both SSL and non-SSL connections allowed
host    all             all             all                     trust
hostssl all             all             all                     trust
EOF
        ;;
    require)
        cat >> "$PGDATA/pg_hba.conf" << EOF

# SSL required, client certs optional
hostssl all             all             all                     trust

# Reject non-SSL connections
hostnossl all           all             all                     reject
EOF
        ;;
    verify-ca)
        cat >> "$PGDATA/pg_hba.conf" << EOF

# SSL + client certificate required (CA verified)
hostssl all             all             all                     trust clientcert=verify-ca

# Reject non-SSL connections
hostnossl all           all             all                     reject
EOF
        ;;
    verify-full)
        cat >> "$PGDATA/pg_hba.conf" << EOF

# SSL + client certificate required (CA + CN verified)
hostssl all             all             all                     trust clientcert=verify-full

# Reject non-SSL connections
hostnossl all           all             all                     reject
EOF
        ;;
esac

echo "pg_hba.conf configuration complete"
